name: Mirror Docker Containers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: alpine
            repo: docker.io
          - image: centos
            repo: docker.io
          - image: haproxy
            repo: docker.io
          - image: jitsi/web
            repo: docker.io
          - image: jitsi/prosody
            repo: docker.io
          - image: jitsi/jicofo
            repo: docker.io
          - image: jitsi/jvb
            repo: docker.io
          - image: ubuntu
            repo: docker.io
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set variables
        id: vars
        run: |
          # access with 'echo ${{ steps.vars.outputs.tag }}'
          echo "tag=${GITHUB_REF#refs/*/}" >> "${GITHUB_OUTPUT}"
          echo "sha=${GITHUB_SHA}" >> "${GITHUB_OUTPUT}"
          echo "repoowner=${GITHUB_REPOSITORY_OWNER,,}" >> "${GITHUB_OUTPUT}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Setup Crane
        uses: imjasonh/setup-crane@v0.4

      - name: Mirror with crane copy
        run: |
          for tag in $(cat ./images/${{ matrix.image }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${{ steps.vars.outputs.repoowner }}/mirror/${{ matrix.repo }}/${{ matrix.image }}:$tag
          done
